vaadin/vaadin-confirm-dialog-flow

pom.xml, vaadin-confirm-dialog-integration-tests/pom.xml, vaadin-confirm-dialog-integration-tests/src/test/java/com/vaadin/flow/component/confirmdialog/test/hiptest/Actionwords.java, vaadin-confirm-dialog-testbench/pom.xml, vaadin-confirm-dialog-testbench/src/license/cval3/header.txt, vaadin-confirm-dialog-testbench/src/license/cval3/license.txt, vaadin-confirm-dialog-testbench/src/license/licenses.properties, vaadin-confirm-dialog-testbench/src/main/java/com/vaadin/flow/component/confirmdialog/testbench/ConfirmDialogElement.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-confirm-dialog-flow/18)
=> Add module for testbench API

pom.xml, vaadin-confirm-dialog-integration-tests/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-confirm-dialog-flow/20)
=> Use stable flow and components

vaadin-confirm-dialog-integration-tests/src/test/java/com/vaadin/flow/component/confirmdialog/test/AbstractParallelTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-confirm-dialog-flow/24)
=> Add platform desired capability for IE

pom.xml, vaadin-confirm-dialog-flow-vaadincom-demo/pom.xml, vaadin-confirm-dialog-integration-tests/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-confirm-dialog-flow/23)
=> Use vaadin parent, skip deploy for some modules

vaadin-confirm-dialog-flow/src/main/java/com/vaadin/flow/component/confirmdialog/ConfirmDialog.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-confirm-dialog-flow/25)
=> Import src version of the component

vaadin-confirm-dialog-flow/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-confirm-dialog-flow/27)
=> prepare v1.0.0-beta3

vaadin-confirm-dialog-flow/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-confirm-dialog-flow/29)
=> prepare 1.0.0

vaadin-confirm-dialog-flow/src/main/java/com/vaadin/flow/component/confirmdialog/ConfirmDialog.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-confirm-dialog-flow/30)
=> Add a javadoc

pom.xml, vaadin-confirm-dialog-flow-vaadincom-demo/pom.xml, vaadin-confirm-dialog-flow/pom.xml, vaadin-confirm-dialog-integration-tests/pom.xml, vaadin-confirm-dialog-integration-tests/webdrivers.xml, vaadin-confirm-dialog-testbench/pom.xml
Prepare for 1.1.0 alpha release, update flow version
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-confirm-dialog-flow/31)
=> Update component version

pom.xml, vaadin-confirm-dialog-flow/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-confirm-dialog-flow/34)
=> Fix resolutions

vaadin-confirm-dialog-flow/pom.xml
Fixes #44
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-confirm-dialog-flow/45)
=> Generate OSGi metadata

vaadin-confirm-dialog-flow/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-confirm-dialog-flow/49)
=> Remove v8 specific metadata from manifest

vaadin-confirm-dialog-flow/src/main/java/com/vaadin/flow/component/confirmdialog/ConfirmDialog.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-confirm-dialog-flow/53)
=> Added api using components

vaadin-confirm-dialog-integration-tests/src/test/java/com/vaadin/flow/component/confirmdialog/test/hiptest/Actionwords.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-confirm-dialog-flow/54)
=> Removed warnings

pom.xml, vaadin-confirm-dialog-flow-vaadincom-demo/pom.xml, vaadin-confirm-dialog-flow/pom.xml, vaadin-confirm-dialog-integration-tests/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-confirm-dialog-flow/58)
=> Update to flow 1.3

pom.xml, vaadin-confirm-dialog-flow-vaadincom-demo/pom.xml, vaadin-confirm-dialog-flow/pom.xml, vaadin-confirm-dialog-integration-tests/pom.xml, vaadin-confirm-dialog-testbench/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-confirm-dialog-flow/59)
=> Bump minor version

vaadin-confirm-dialog-flow-vaadincom-demo/pom.xml, vaadin-confirm-dialog-integration-tests/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-confirm-dialog-flow/62)
=> Update dependencies to stable

pom.xml, vaadin-confirm-dialog-flow-demo/pom.xml, vaadin-confirm-dialog-flow-demo/src/main/java/com/vaadin/flow/component/confirmdialog/ConfirmDialogView.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-confirm-dialog-flow/63)
=> Rename demo module

vaadin-confirm-dialog-integration-tests/src/main/java/com/vaadin/flow/component/confirmdialog/examples/BasicUseView.java, vaadin-confirm-dialog-integration-tests/src/test/java/com/vaadin/flow/component/confirmdialog/test/BasicUseIT.java, vaadin-confirm-dialog-testbench/src/main/java/com/vaadin/flow/component/confirmdialog/testbench/ConfirmDialogElement.java
Fixes #52
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-confirm-dialog-flow/64)
=> Get header and message texts via properties in TB element

vaadin-confirm-dialog-flow/src/main/java/com/vaadin/flow/component/confirmdialog/ConfirmDialog.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-confirm-dialog-flow/74)
=> Fix theming in npm mode

vaadin-confirm-dialog-flow-demo/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-confirm-dialog-flow/75)
=> Demo should use  JsModule annotated elements

README.md, vaadin-confirm-dialog-flow-demo/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-confirm-dialog-flow/77)
=> Adding a `war` profile for demos

pom.xml, vaadin-confirm-dialog-flow-demo/pom.xml, vaadin-confirm-dialog-flow/pom.xml, vaadin-confirm-dialog-integration-tests/pom-bower-mode.xml, vaadin-confirm-dialog-integration-tests/pom.xml, vaadin-confirm-dialog-testbench/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-confirm-dialog-flow/82)
=> Prepare RC

vaadin-confirm-dialog-flow-demo/src/main/java/com/vaadin/flow/component/confirmdialog/ConfirmDialogView.java, vaadin-confirm-dialog-integration-tests/src/main/java/com/vaadin/flow/component/confirmdialog/examples/Features.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-confirm-dialog-flow/83)
=> Remove workaround for https://github.com/vaadin/flow/issues/5619

pom.xml, vaadin-confirm-dialog-flow-demo/pom.xml, vaadin-confirm-dialog-flow/pom.xml, vaadin-confirm-dialog-integration-tests/pom-bower-mode.xml, vaadin-confirm-dialog-integration-tests/pom.xml, vaadin-confirm-dialog-testbench/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-confirm-dialog-flow/85)
=> Bump versions to RC2

vaadin-confirm-dialog-flow-demo/src/main/java/com/vaadin/flow/component/confirmdialog/ConfirmDialogView.java
Closes #71
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-confirm-dialog-flow/86)
=> Show how to open dialog

vaadin-confirm-dialog-flow/pom.xml, vaadin-confirm-dialog-flow/src/main/java/com/vaadin/flow/component/confirmdialog/ConfirmDialog.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-confirm-dialog-flow/101)
=> Update web component version to 1.1.5

pom.xml, vaadin-confirm-dialog-flow-demo/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-confirm-dialog-flow/102)
=> Fix configuration for release

pom.xml, vaadin-confirm-dialog-flow-demo/pom.xml, vaadin-confirm-dialog-integration-tests/pom-bower-mode.xml, vaadin-confirm-dialog-integration-tests/pom.xml, vaadin-confirm-dialog-testbench/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-confirm-dialog-flow/103)
=> Use snapshots

vaadin-confirm-dialog-flow-demo/pom.xml, vaadin-confirm-dialog-integration-tests/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-confirm-dialog-flow/111)
=> Set versions on flow-maven-plugin Fix for the snapshot build

vaadin-confirm-dialog-flow/src/main/java/com/vaadin/flow/component/confirmdialog/ConfirmDialog.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-confirm-dialog-flow/116)
=> Bump webcomponent to 1.1.6 in master

pom.xml, vaadin-confirm-dialog-testbench/pom.xml
allowing to override it to stable version on release
=> Set vaadin-button-testbench version as property

vaadin-confirm-dialog-flow-demo/src/main/java/com/vaadin/flow/component/confirmdialog/ConfirmDialogView.java
For users to be able to use code correctly by copy-pasting
Depends on https://github.com/vaadin/flow/pull/8199/files
=> Add add-method call to make code complete

vaadin-confirm-dialog-flow-demo/src/main/java/com/vaadin/flow/component/confirmdialog/ConfirmDialogView.java
For users to be able to use code correctly by copy-pasting
Depends on https://github.com/vaadin/flow/pull/8199/files
=> Add add-method call to make code complete (#125)
